### ISSUE TITLE
Typeahead support vue events?

### ISSUE THREAD

**Issue by tehjrow** [wffranco/vue-strap#124]
I can't seem to get the keyup event to fire on the typeahead.  Is there any way to do that?

    `<typeahead 
            v-model="name"
            placeholder="name" 
            async-key="data" 
            async="http://api.address.here" 
            :template="asyncTemplate" 
            :on-hit="callBack"
            v-on:keyup="runThisFunction" >
        </typeahead> `

**Comment by Ben52** [comment]
Wrap it in your own element: 
```
<span v-on:keyup="runThisFunction">
   <typeahead 
        v-model="name"
        placeholder="name" 
        async-key="data" 
        async="http://api.address.here" 
        :template="asyncTemplate" 
        :on-hit="callBack" >
    </typeahead> 
</span>
