### ISSUE TITLE
Modal docs suggestions

### ISSUE THREAD

**Issue by ropeladder** [wffranco/vue-strap#19]
The 'Zoom Modal' cannot be dismissed using either the 'Close' button or the top corner 'x'. I think this is because you don't have `@cancel='zoomModal = false'` in the tags.

Also, I couldn't figure out what happened to the 'dismissable' directive from the older version of vue-strap until I realized that it was always there unless you slotted in a different header. Might be good to explain this.

**Comment by wffranco** [comment]
Yep that was done that way intentionally, in the example code was missing too.
But now I know that looks confusing, so I fix it.
