### ISSUE TITLE
Tootltip not working

### ISSUE THREAD

**Issue by bigperson** [wffranco/vue-strap#24]
> [Vue warn]: Unknown custom element: <tooltip> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 

`import tooltip from 'vue-strap/src/Tooltip.vue';`

```
<tooltip effect="scale" placement="bottom" content="Lorem ipsum dolor sit amet consectetur adipisicing elit, sed do eiusmod">
  <button class="btn btn-default">tooltip on bottom</button>
</tooltip>
```

`components: {
                tooltip
            }`

Vue 2.1.6

**Comment by wffranco** [comment]
Some minutes ago I fix popover & tooltip.
Update and try again.

**Comment by bigperson** [comment]
Well, it works.
But now the problem components tooltip and popover wraps buttons in the <span></span> ((.  How can I get rid of it?

**Comment by wffranco** [comment]
I'm trying to think in a solution, but by for now is not possible, vue2 force to have only one root node, so need a wrapper for the user content plus the tooltip.
