### ISSUE TITLE
Suggestion / question for Aside in v2

### ISSUE THREAD

**Issue by fabd** [wffranco/vue-strap#26]
Hello

You seem active in updating v2 so I thought I'd share some thoughts here about the [Aside component](https://github.com/wffranco/vue-strap/blob/v2/src/Aside.vue) I'm trying to include onto my site, and maybe learn a few things =)

**Issue**
I am seeing a glitch where the `aside` div seems to display at translateX(0) for a frame, then the animation kicks in. This happens erratically. it didn't show at all on a simple test page, but it shows since I included it in a more complex site.

I wonder how to tackle this. Is Vue `v-if` causing the div to appear but not kicking in the animation within the same frame? A solution perhaps would be to set visibility hidden by default and then visible on anim "enter"?

**Other thoughts/comments**

_( edit: cf. suggested changes in gist below )_

(ps: the first four points above seem to work for me, on desktop , untested on mobile)

_(edit: removed suggestion about dynamic instancing , that's more specific to my project)_

PS: feel free to close issue if need be, this is mostly for discussion. I am hacking this component for my own site which is why I don't have a straight up pull request plus you may not like some of these changes, I don't know. So I'm bringing some ideas mostly.

**Comment by fabd** [comment]
Created a pull request for the glitch, due to first frame appearing at `translateX(0)` position.

**Comment by fabd** [comment]
Here is a gist showing some suggested changes. I'm not creating a pull request because I have so much work on my site already, so I'll leave it for you or anybody interested to merge the changes, or not. Just contributing a little something.

https://gist.github.com/fabd/f17c9cfe8f9b1d1bd503cfb413ead1da

Main suggested changes:

* adding `.aside-backdrop` div to the template, surrounded by <transition>
* subscribing to the transition events in transition `@before-enter` and `@leave`
* @touchmove.stop.prevent on the backdrop (optional, saw this in another component)
* add the transition css `.mask-enter, .mask-leave-active`

PS: what's `.aside-open.has-push-right`in the css ?

**Comment by wffranco** [comment]
Can you do a live demo for that?

Use https://jsfiddle.net/ if you want :D

**Comment by fabd** [comment]
Sure, I'll see if I can make one soon, didn't think about it.

**Comment by fabd** [comment]
Hey, I thought I'd try a pull request. I cloned repo but npm docs doesn't work. Console says `Cannot find module "src/ButtonGroup.vue"` (that file uses a lowercase "buttonGroup.vue").  Is that something to do with the case of filenames, or is the repo not building atm?
