### ISSUE TITLE
Alert doesn't work with duration=0

### ISSUE THREAD

**Issue by ropeladder** [wffranco/vue-strap#3]
The Alert component doesn't appear to last indefinitely when duration is set to zero (like it did in 1.0). It maybe as simple as replacing the `val` watch function with:

```
    val: delayer(function (val) {
      if(this.durationNum > 0) {
        this.val = false
        this.$emit('input', val)
      }
    }, 'durationNum'),
```

I tried creating a pull request from my local copy of wffranco/master but I'm pretty new to git and it didn't seem to work. (maybe because I don't have permission? or I could be doing something else wrong)

**Comment by senid231** [comment]
@ropeladder, I created PR for you #7

**Comment by wffranco** [comment]
bug fixed
