### ISSUE TITLE
Get it up on CDN?

### ISSUE THREAD

**Issue by eklem** [wffranco/vue-strap#38]
Hi, and thanks for updating vue-strap to be compatible with v.2 of vuejs!

Since not much is happening over at yuche/vue-strap, have you thought about adding this fork to a CDN?

**Comment by wffranco** [comment]
Is difficult to do it without acces to the npm project. But some cdn let you work direct with any file, liek rawgit.com:
https://cdn.rawgit.com/wffranco/vue-strap/a357d4c32fab63ac700c4d5ba9087b634ed8a1ff/dist/vue-strap.js

**Comment by eklem** [comment]
Thanks, I'll use rawgit.com! And keep up the good work =)
