### ISSUE TITLE
Modal open by default

### ISSUE THREAD

**Issue by lbineau** [wffranco/vue-strap#49]
Hello,

I think I found a bug with modal component.

```vue
// myVal is set to TRUE by default
<modal :value="myVal">
  ...
</modal>
```
### Expected
modal should appear

### Result
modal doesn't appear

### Problem
modal only check for value changes but does not observe it on mounted callback
```javascript
watch: {
    value (val, old) {
      if (val !== old) this.transitionstart()
    }
}
```

### Potential solution
```javascript
mounted () {
  if (this.value) this.transitionstart()
}

**Comment by wffranco** [comment]
Fixed. Thanks for your help.
