### ISSUE TITLE
Select Placeholder does not work

### ISSUE THREAD

**Issue by infernobass7** [wffranco/vue-strap#5]
I noticed after install this package that v-select does not display a placeholder in the event that there has not been a value selected yet.

(Overall the upgrades in this package are great compared to the original)

**Comment by webnoob** [comment]
I came to report the same thing so appear to be experiencing the same issue. It does appear to work sometimes but I've not found out when / why. If I find the pattern, I'll add some more information.

**Comment by wffranco** [comment]
I'm fixing a lot of details right now and the placeholder work right. I add the placeholder in the test page.
