### ISSUE TITLE
Can I set the initial value to the Select?

### ISSUE THREAD

**Issue by larryu** [wffranco/vue-strap#65]
After I set all the values to the Select component, it always display Nothing Selected. Is there any way to set it to any value?

**Comment by larryu** [comment]
Closed. Found the way.

**Comment by klexxp** [comment]
Nice for you!
Could you tell us how you did it?

Thanks

**Comment by larryu** [comment]
@klexxp Here is the sample source code.

                <v-select
                        v-model="testValue"
                        :options="testOptions">
                </v-select>
If testValue is pre-set to a value, then it will show that value.
But still, sometimes it is a little bit tricky.

**Comment by yunyu** [comment]
I couldn't get this working consistently, it only works with direct values (e.g. data: { testValue: 'test' }) and not nested values. This seems like broken behavior, I'm not sure why val is a thing anyways (what's wrong with $emit for everything)?
