### ISSUE TITLE
Datepicker value mutating fix

### ISSUE THREAD

**Issue by purepear** [wffranco/vue-strap#8]
Here is a gist which fixes the warnig and adds iconsFont property so you can use glyphicon or fa (Font awesome)

Also removes the default width ... works better with bootstrap grid
Also fixes `window.removeEventListner` typo

https://gist.github.com/purepear/df5fb8a6cc862071bb07ca5d059a0ade

**Comment by wffranco** [comment]
I don't touched too much the code of datepicker but please update to the last version and make a pull request, I'll check it.
