### ISSUE TITLE
Aside close button not working

### ISSUE THREAD

**Issue by xorbis** [wffranco/vue-strap#80]
I have this template:
```
<sidebar :show="showRight" placement="right" :header="t('Sitemap')" :width="300">
	<ul class="list-unstyled">
		<li v-for="(url, key) in rest.sitemap"><a @click="rest.url = key; showRight = false">{{key}}</a></li>
	</ul>
</sidebar>
```

Which is a list of URL that once any is clicked, they properly close the aside component.
On the other hand, the close button and clicking the transparent overlay, does not close the aside.

In the documentation, the aside mention v-model should be used to show or hide the aside but it doesn't work and the console displays a warning about the missing show property.

**Comment by PsychicCat** [comment]
yeah I think the documentation is off.

Add this: `@close="showRight = false"` to your sidebar attributes and it should close properly.

**Comment by xorbis** [comment]
That fixed it, thanks a lot!
