### ISSUE TITLE
Syntax error on IE 11

### ISSUE THREAD

**Issue by zerosrat** [wffranco/vue-strap#98]
I have encountered the same same issue as [#83](https://github.com/wffranco/vue-strap/issues/83). 

My solution is to use babel-loader to tranform vue-strap module to es5 in `webpack.config.js` file of my project.

``` js
function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

module.exports = {
  ...
  {
    test: /\.js$/,
    loader: 'babel-loader',
    include: [resolve('src'), resolve('test'), resolve('node_modules/vue-strap/src')]
  }
}
```

 @wffranco, do you  have any better suggestions?

**Comment by larryu** [comment]
@zerosrat I think this is the pretty better way to solve the problem.
Check this way. Pretty the same.
[](https://github.com/JeffreyWay/laravel-mix/issues/631)

**Comment by zerosrat** [comment]
@larryu Thanks for your reply. As you said, your solution is similar to mine. Both of the solutions use babel-loader to transform es6 syntax to es5.
